include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_linter

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

dart_code_linter:
  rules:
    - no-magic-number:
        severity: warning
        allowed: [-1, 0, 1, 2]
        allow-only-once: false
    - no-empty-block
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - avoid-nested-conditional-expressions
    - prefer-moving-to-variable
